id: P003088
initial_creation_type: ocr
source_metadata:
  id: bdr:W30066
  title: རྗེ་ཀུན་དགའ་ཐུགས་རྗེ་དཔལ་བཟང་པོའི་རྣམ་ཐར
  author: ''
  volumes:
    9b5e3f4d284949519fe7930ded7c292e:
      image_group_id: I6089
      title: ''
      volume_number: 1
      total_pages: 458
